routes/web.php
<?php
namespace App\Http\Controllers;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TasksController;
use App\Http\Controllers\WorkersController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('/tasks', TasksController::class);
// Labor Routes//
Route::post('/addWorker','App\Http\Controllers\WorkersController@store');
Route::delete('/deleteWorker/{id}','App\Http\Controllers\WorkersController@destroy');
// Parts Routes//
Route::post('/addPart','App\Http\Controllers\PartsController@store');
Route::delete('/deletePart/{id}','App\Http\Controllers\PartsController@destroy');
// Issues Routes
Route::post('/addIssue','App\Http\Controllers\IssuesController@store');
Route::delete('/deleteIssue/{id}','App\Http\Controllers\IssuesControllerr@destroy');

app/Models/tasks.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;


class tasks extends Model
{   
    public $timestamps = false;
    use HasFactory;
   
    protected $fillable = ["taskName","taskPrice","laborTotal","partsTotal","taskTotal"];

    public function workers(){
        return $this->hasMany(workers::class);
    }
    public function parts(){
        return $this->hasMany(parts::class);
    }
    public function issues(){
        return $this->hasMany(issues::class);
    }

}

app/Http/Controllers/TasksController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use App\Models\tasks;
use App\Models\workers;
use App\Models\parts;
class TasksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tasks = tasks::all();
         foreach($tasks as $task) {
        $partsTotal = DB::table('parts')->where('tasks_id' ,'=', $task->id)->sum('partsTotal');
        $workersTotal = DB::table('workers')->where('tasks_id' ,'=', $task->id)->sum('workersTotal');
        DB::table('tasks')->where('id', '=', $task->id)->update(['laborTotal'=> $workersTotal, 'partsTotal'=>$partsTotal]);
        }
        return view('tasks.index', compact('tasks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tasks');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {   
        if ($request->has('taskName')){
        $storeData = $request->all();
        $tasks = tasks::create($storeData);
        return redirect('tasks');
        }
      
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        tasks::destroy($id);
        return redirect('tasks');
        
    }
}

resources/views/tasks/index.blade.php
@extends('tasks.layout')
@section('content')

<div>
  <form action="/tasks" class="mt-3" method="POST">
    {{ csrf_field() }}
    <label for="taskName">Add Task</label>
    <input class="form-control mb-3" type="text" id="taskName" name="taskName" />
  </form>

  <table class="table table-bordered table-striped">

    <thead>
      <tr>
        <th scope="col">Tasks</th>
        <th scope="col">Actions</th>
        <th scope="col">Labor Total</th>
        <th scope="col">Parts Total</th>
        <th scope="col">Subtotal</th>
        <td></td>
      </tr>
    </thead>
    <tbody class="text-center">
      @php
        $grandtotal = 0;    
      @endphp
      @foreach($tasks as $task)
      <tr>
        <td style="overflow: hidden;">{{$task->taskName}}<table class="table ms-2 mt-5 intable">
            @if(isset($task->workers))
            @foreach ($task->workers as $worker)


            <tr style="font-size: 9px;width: 10%;">
              <td>
                <form method="POST" action="/deleteWorker/{{$worker->id}}">
                  {{ csrf_field() }}
                  @method('delete')
                  <input type="hidden" name="_method" value="delete">
                  <button type="submit" onclick="confirm('Are you sure?')"
                    class="btn btn-danger btn-icon deleteW">
                    <i>X</i>

                  </button>
                </form>
              </td>
              <td>{{$worker->workerName}}</td>
              <td>{{$worker->workRate}}</td>
              <td>{{$worker->workersTotal}}</td>
            </tr>
            @php
            
            @endphp
            @endforeach
            @endif
            @if(isset($task->parts))
            @foreach ($task->parts as $part)


            <tr style="font-size: 9px;width: 10%;">
              <td>
                <form method="POST" action="/deletePart/{{$part->id}}">
                  {{ csrf_field() }}
                  @method('delete')
                  <input type="hidden" name="_method" value="delete">
                  <button type="submit" onclick="return confirm('Are you sure?')"
                    class="btn btn-danger btn-icon deleteW">
                    <i>X</i>

                  </button>
                </form>
              </td>
              <td>{{$part->partName}}</td>
              <td>{{$part->partQty}}</td>
              <td>{{$part->partsTotal}}</td>
            </tr>
            </form>
            @php
           
            @endphp
            @endforeach
            @endif

          </table>
        </td>

        <td align="left">
          {{-- Modal Buttons --}}
          <button type="button" class="btn btn-primary position-relative me-0 " data-bs-toggle="modal"
            data-bs-target="#modal{{$task->id}}">
            <i class="fa-solid fa-person"></i>
            @if($task->workers->isNotEmpty())
            <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
              {{count($task->workers)}}
            </span>
            @endif

          </button>
          <button type="button" class="btn btn-primary position-relative mx-1" data-bs-toggle="modal"
            data-bs-target="#pmodal{{$task->id}}">
            <i class="fa-solid fa-gear"></i>
            @if($task->parts->isNotEmpty())
            <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
              {{count($task->parts)}}
            </span>
            @endif
          </button>
          <button type="button" class="btn btn-primary position-relative mx-1" data-bs-toggle="modal"
            data-bs-target="#imodal{{$task->id}}">
            <i class="fa-solid fa-circle-exclamation"></i>
          </button>
          {{-- Modal Body --}}
          <div class="modal fade" id="modal{{$task->id}}" tabindex="-1" aria-labelledby="exampleModalLabel"
            aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <form method="POST" action="{{url('/addWorker')}}">
                    {{ csrf_field() }}
                    @method('post')
                    <label for="workerName">Name</label>
                    <input type="text" name="workerName" class="form-control" />
                    <label for="workerRate">Rate</label>
                    <input type="text" name="workRate" class="form-control" />
                    <label for="workHours">Work Hours</label>
                    <input type="text" name="workHours" class="form-control mb-2" />
                    <input type="hidden" name="tasks_id" value="{{$task->id}}" />
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" name="form2" class="btn btn-primary">Save changes</button>
                  </form>
                </div>
                <div class="modal-footer">

                </div>
              </div>
            </div>
          </div>
          <!--Parts Modal Body-->
          <div class="modal fade" id="pmodal{{$task->id}}" tabindex="-1" aria-labelledby="exampleModalLabel"
            aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <form method="POST" action="{{url('/addPart')}}">
                    {{ csrf_field() }}
                    @method('post')
                    <label for="partName">Part Name</label>
                    <input type="text" name="partName" class="form-control" />
                    <label for="partQty">Quantity</label>
                    <input type="text" name="partQty" class="form-control" />
                    <label for="partPrice">Part Price</label>
                    <input type="text" name="partPrice" class="form-control mb-2" />
                    <input type="hidden" name="tasks_id" value="{{$task->id}}" />
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" name="form2" class="btn btn-primary">Save changes</button>
                  </form>
                </div>
                <div class="modal-footer">

                </div>
              </div>
            </div>
          </div>
          <!--Issues Modal Body-->
          <div class="modal fade" id="imodal{{$task->id}}" tabindex="-1" aria-labelledby="exampleModalLabel"
            aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <form method="POST" action="{{url('/addIssue')}}">
                    {{ csrf_field() }}
                      <em><strong>Title</strong></em>
                      <input type="text" class="form-control mb-2" name="title"/>
                      <em><strong>Content</strong></em>
                      <textarea class="form-control" name="content"></textarea>
                      <button type="submit">Add</button>
                   </form>
                </div>
                <div class="modal-footer">

                </div>
              </div>
            </div>
          </div>
        </td>
        @if(isset($task->laborTotal))
        <td>{{$task->laborTotal}}</td>
        @else
        <td>0</td>
        @endif
        <td>{{$task->partsTotal}}</td>
        @php
            $subtotal = $task->partsTotal + $task->laborTotal
        @endphp
        <td>{{$subtotal}}</td>
        <td>
          <form method="POST" action="{{ route('tasks.destroy',$task->id) }}">
            {{ csrf_field() }}
            @method('DELETE')
            <input type="hidden" name="_method" value="delete">
            <button type="submit" onclick="return confirm('Remove whole task?')" class="btn btn-danger btn-icon">
              <i>Delete</i>
            </button>
          </form>
        </td>
      </tr>
      @php
          $grandtotal = $grandtotal  + $subtotal
      @endphp
      @endforeach
    </tbody>
  </table>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
  </script>
</div>

<footer>
  <h6>Taxes : &#8369; 0.00</h6>
  <h6>Additional Fees : &#8369; 0.00</h6>
  <h4>Subtotal : &#8369; 0.00</h4>
  <h2>Total : &#8369; {{$grandtotal}}</h2>
</footer>
@endsection